In [3]:
import numpy as np
from sklearn import preprocessing

In [12]:
a = [1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 10]
a = np.asarray(a)
b = np.asarray(b)

scaler = preprocessing.MinMaxScaler()
scaled = scaler.fit_transform(a.reshape(-1, 1))
scaled2 = scaler.transform(b.reshape(-1, 1))
print(scaled)
print(scaled2)

inverse = scaler.inverse_transform(scaled)
inverse2 = scaler.inverse_transform(scaled2)
print(inverse)
print(inverse2)

[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]
[[1.25]
 [1.5 ]
 [1.75]
 [2.  ]
 [2.25]]
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]
[[ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]]
